### ISSUE TITLE
Code examples not appearing during "Color" segment

### ISSUE THREAD

**Issue by rruubboott** [processing/Processing-Hour-Of-Code#45] opened 2013-11-27 12:25 UTC
During the segment on "Color", the examples Dan is speaking about do not appear in the code window (for instance, stroke() and fill()...and the final example does not appear at the end) On all other segments they appear on time, but they don't appear at all during this section.
Using Firefox on Mac OS X 10.9.

**Comment by ashleyjamesbrown** [comment] 2013-11-27 12:30
Issue also reported on
Windows 7 64 bit using Google Chrome Version 31.0.1650.57 m

**Comment by scottgarner** [comment] 2013-11-27 13:03
Hmm. I'm unable to reproduce this. Did it happen when playing directly through from "Shapes" or when clicking on "Color" and starting there?

**Comment by rruubboott** [comment] 2013-11-27 13:09
When playing directly through from "Shapes"
I just tried it by going directly to "Color" and it worked fine, but when I played from the start earlier, the "Color" section never replaced my old code and it never added what Dan was talking about.

**Comment by ashleyjamesbrown** [comment] 2013-11-27 13:26
Seems if clicking on directly it works OK now. Ill try going through from Shapes and let you know

**Comment by scottgarner** [comment] 2013-11-30 05:16
I've been unable to reproduce this, but have gone back through and tried to make things a little more aggressive about setting state when a new video starts.

I'm going to close this issue, but I bet just the right (wrong) circumstances with Popcorn and Vimeo could still cause problems.

**Closed as completed by scottgarner** 2013-11-30 05:16 UTC
